# Generated by Django 5.2.3 on 2025-06-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ラベル名"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
            ],
            options={
                "verbose_name": "オブジェクトラベル",
                "verbose_name_plural": "オブジェクトラベル",
                "db_table": "object_labels",
            },
        ),
        migrations.RenameModel(
            old_name="AnalysisLog",
            new_name="AiAnalysisLog",
        ),
    ]
